version: "3"

services:
  mongodb:
    image: mongo:5.0-focal
    restart: unless-stopped    
    ports:
      - :27017
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongodb
    build:
      context: .      
    restart: unless-stopped    
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ejemplo
      
volumes:
  db: